spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vistapet_dev
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  # cria/atualiza tabelas automaticamente (apenas dev)
    show-sql: true
